# Generated by Django 4.1.3 on 2024-05-03 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nome_genero', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_jogo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('data_lancamento', models.DateField()),
                ('classificacao_etaria', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('desenvolvedor', models.CharField(max_length=100)),
                ('genero', models.ManyToManyField(to='api.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
