# Generated by Django 4.1.3 on 2024-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='jogo',
            name='genero',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
