# Generated by Django 4.1.3 on 2024-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_jogo_genero_delete_genero_jogo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
