# Generated by Django 4.1.3 on 2024-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_jogo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
